"""hello

Revision ID: 25c2fea2f5e1
Revises: 4bb8975a9c43
Create Date: 2014-06-26 14:23:39.491693

"""

# revision identifiers, used by Alembic.
revision = '25c2fea2f5e1'
down_revision = '4bb8975a9c43'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
